name: auth_state_manager
description: This package helps you to monitor auth statuses in your app.
version: 0.1.2
homepage: https://github.com/abdulbositKomilovuz/auth_state_manager.git

environment:
  sdk: ">=2.18.5 <3.10.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter: null
